packages:
  - "packages/*"
  - "packages/app/vendor/novel/packages/*"
  - "packages/app/vendor/liveblocks/packages/*"
  - "packages/app/vendor/liveblocks/shared/*"
  - "packages/app/vendor/headless-tree/packages/*"
  - "packages/app/vendor/remix/packages/*"
  - "packages/app/vendor/tiptap/packages/*"
  - "packages/app/vendor/tiptap/packages-deprecated/*"
  - "packages/app/vendor/mastra/packages/rag"
  - "packages/app/vendor/polar"
  - "packages/app/vendor/presence"
  - "packages/app/vendor/rate-limiter"
  - "packages/app/vendor/r2"

overrides:
  "@tiptap/y-tiptap": "3.0.0"
  convex: "1.42.2"
  marked: "17.0.1"
  react: "19.2.4"
  react-dom: "19.2.4"

onlyBuiltDependencies:
  - "@clerk/shared"
  - core-js
  - core-js-pure
  - esbuild
  - msw
